default_platform(:ios)
platform :ios do
  desc "Build and upload to TestFlight"
  lane :testflight_deploy do
    match(type: "appstore", app_identifier: ["com.yourcompany.gymgenie", "com.yourcompany.gymgenie.GymGenieShare"], readonly: is_ci, git_url: ENV["MATCH_GIT_URL"])
    increment_build_number(xcodeproj: "GymGenie.xcodeproj", build_number: Time.now.strftime("%Y%m%d%H%M").to_i)
    build_app(scheme: "GymGenie", export_method: "app-store", include_bitcode: false)
    upload_to_testflight(skip_waiting_for_build_processing: true, notify_external_testers: false)
  end
end
